// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monthly_Bill_Calculator.Data;

#nullable disable

namespace Monthly_Bill_Calculator.Migrations
{
    [DbContext(typeof(CalcAppDbContext))]
    [Migration("20260212190155_InitialDbDesign")]
    partial class InitialDbDesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.CentralHeating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CentralHeatings");
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.ColdWater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ColdWaters");
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.Electricity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Electricities");
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.HotWater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HotWaters");
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.Month", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CentralHeatingId")
                        .HasColumnType("int");

                    b.Property<int?>("ColdWaterId")
                        .HasColumnType("int");

                    b.Property<int?>("ElectricityId")
                        .HasColumnType("int");

                    b.Property<int?>("HotWaterId")
                        .HasColumnType("int");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int?>("NaturalGasId")
                        .HasColumnType("int");

                    b.Property<int?>("SteamId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CentralHeatingId");

                    b.HasIndex("ColdWaterId");

                    b.HasIndex("ElectricityId");

                    b.HasIndex("HotWaterId");

                    b.HasIndex("NaturalGasId");

                    b.HasIndex("SteamId");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.NaturalGas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NaturalGases");
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.Steam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Steams");
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.Month", b =>
                {
                    b.HasOne("Monthly_Bill_Calculator.DB_Models.CentralHeating", "CentralHeating")
                        .WithMany()
                        .HasForeignKey("CentralHeatingId");

                    b.HasOne("Monthly_Bill_Calculator.DB_Models.ColdWater", "ColdWater")
                        .WithMany()
                        .HasForeignKey("ColdWaterId");

                    b.HasOne("Monthly_Bill_Calculator.DB_Models.Electricity", "Electricity")
                        .WithMany()
                        .HasForeignKey("ElectricityId");

                    b.HasOne("Monthly_Bill_Calculator.DB_Models.HotWater", "HotWater")
                        .WithMany()
                        .HasForeignKey("HotWaterId");

                    b.HasOne("Monthly_Bill_Calculator.DB_Models.NaturalGas", "NaturalGas")
                        .WithMany()
                        .HasForeignKey("NaturalGasId");

                    b.HasOne("Monthly_Bill_Calculator.DB_Models.Steam", "Steam")
                        .WithMany()
                        .HasForeignKey("SteamId");

                    b.Navigation("CentralHeating");

                    b.Navigation("ColdWater");

                    b.Navigation("Electricity");

                    b.Navigation("HotWater");

                    b.Navigation("NaturalGas");

                    b.Navigation("Steam");
                });
#pragma warning restore 612, 618
        }
    }
}
