// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monthly_Bill_Calculator.Data;

#nullable disable

namespace Monthly_Bill_Calculator.Migrations
{
    [DbContext(typeof(CalcAppDbContext))]
    [Migration("20260214171216_UpdateUtilityModel")]
    partial class UpdateUtilityModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.CentralHeating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CentralHeatings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Consumption = 100.0,
                            Price = 0.15m
                        });
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.ColdWater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ColdWaters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Consumption = 5.0,
                            Price = 2.50m
                        });
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.Electricity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Electricities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Consumption = 120.0,
                            Price = 0.20m
                        });
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.HotWater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("HotWaters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Consumption = 3.0,
                            Price = 4.00m
                        });
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.Month", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CentralHeatingId")
                        .HasColumnType("int");

                    b.Property<int?>("ColdWaterId")
                        .HasColumnType("int");

                    b.Property<int?>("ElectricityId")
                        .HasColumnType("int");

                    b.Property<int?>("HotWaterId")
                        .HasColumnType("int");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int?>("NaturalGasId")
                        .HasColumnType("int");

                    b.Property<int?>("SteamId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CentralHeatingId");

                    b.HasIndex("ColdWaterId");

                    b.HasIndex("ElectricityId");

                    b.HasIndex("HotWaterId");

                    b.HasIndex("NaturalGasId");

                    b.HasIndex("SteamId");

                    b.ToTable("Months");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CentralHeatingId = 1,
                            ColdWaterId = 1,
                            ElectricityId = 1,
                            HotWaterId = 1,
                            MonthNumber = 11,
                            NaturalGasId = 1,
                            SteamId = 1,
                            Year = 2025
                        },
                        new
                        {
                            Id = 2,
                            MonthNumber = 12,
                            Year = 2025
                        },
                        new
                        {
                            Id = 3,
                            MonthNumber = 1,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.NaturalGas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("NaturalGases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Consumption = 50.0,
                            Price = 1.20m
                        });
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.Steam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Consumption")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Steams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Consumption = 10.0,
                            Price = 3.00m
                        });
                });

            modelBuilder.Entity("Monthly_Bill_Calculator.DB_Models.Month", b =>
                {
                    b.HasOne("Monthly_Bill_Calculator.DB_Models.CentralHeating", "CentralHeating")
                        .WithMany()
                        .HasForeignKey("CentralHeatingId");

                    b.HasOne("Monthly_Bill_Calculator.DB_Models.ColdWater", "ColdWater")
                        .WithMany()
                        .HasForeignKey("ColdWaterId");

                    b.HasOne("Monthly_Bill_Calculator.DB_Models.Electricity", "Electricity")
                        .WithMany()
                        .HasForeignKey("ElectricityId");

                    b.HasOne("Monthly_Bill_Calculator.DB_Models.HotWater", "HotWater")
                        .WithMany()
                        .HasForeignKey("HotWaterId");

                    b.HasOne("Monthly_Bill_Calculator.DB_Models.NaturalGas", "NaturalGas")
                        .WithMany()
                        .HasForeignKey("NaturalGasId");

                    b.HasOne("Monthly_Bill_Calculator.DB_Models.Steam", "Steam")
                        .WithMany()
                        .HasForeignKey("SteamId");

                    b.Navigation("CentralHeating");

                    b.Navigation("ColdWater");

                    b.Navigation("Electricity");

                    b.Navigation("HotWater");

                    b.Navigation("NaturalGas");

                    b.Navigation("Steam");
                });
#pragma warning restore 612, 618
        }
    }
}
